name: Issue Label Automation

on:
  issues:
    types:
      - closed

env:
  PROJECT_NAME: Roadmap

jobs:
  issue_labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Remove Priority and Task labels
        if: "github.event.action == 'closed'"
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "âš ï¸å„ªå…ˆåº¦ï¼šé«˜,ğŸ”¥å„ªå…ˆåº¦ï¼šä¸­,ğŸ’å„ªå…ˆåº¦ï¼šä½,ğŸ¡ã‚¿ã‚¹ã‚¯"
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
