name: issue label automation
on:
  issues:
    types:
      - closed
      
env:
  PROJECT_NAME: Roadmap
jobs:
  issue_labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Remove Priority label
        if: "github.event.action == 'closed'"
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "ğŸ’æ©Ÿèƒ½å®Ÿè£…"
          remove-labels: "âš ï¸å„ªå…ˆåº¦ï¼šé«˜"
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
